# Cấu hình dự án Smarthome V1 (Step 1)

# 1. Cấu hình Board
CONFIG_BOARD_FLASH_SIZE := 2
CONFIG_CHIP_NAME := BL602

# 2. BẬT WIFI & MẠNG (QUAN TRỌNG ĐỂ FIX LỖI)
CONFIG_WIFI := 1
CONFIG_LwIP := 1
CONFIG_MBEDTLS := 1
CONFIG_RF := 1

# 3. BẬT BLUETOOTH
CONFIG_BLE := 1
CONFIG_BT := 1
CONFIG_BT_NIMBLE := 1
CONFIG_BLE_ACT_MAX := 1

# 4. BẬT LƯU TRỮ FLASH
CONFIG_EASYFLASH_ENABLE := 1
CONFIG_PARTITION := 1

# 5. Cấu hình Hệ thống & RAM
CONFIG_BL_IOT_FW_AP := 1
CONFIG_ENABLE_PSM_RAM := 1
CONFIG_BL602_USE_ROM_DRIVER := 1

# Stack size cần lớn cho BLE + Wifi
CONFIG_SYS_APP_TASK_STACK_SIZE := 4096
CONFIG_SYS_APP_TASK_PRIORITY := 15

# Các module phụ trợ
CONFIG_FREERTOS_TICKLESS_MODE := 0
CONFIG_SYS_VFS_ENABLE := 1
CONFIG_SYS_VFS_UART_ENABLE := 1
CONFIG_SYS_AOS_LOOP_ENABLE := 1
CONFIG_SYS_BLOG_ENABLE := 1
CONF_ENABLE_COREDUMP := 1

# Danh sách log (Giữ nguyên)
LOG_ENABLED_COMPONENTS := blog_testc hosal loopset looprt bloop blink